---
# tasks file for nginx

- name: copy systmd unit file
  template: src=nginx.service.j2 dest=/etc/systemd/system/nginx.service mode=0755

- name: add github ssh key
  copy: 
    src: /Users/hsutsungchun/.ssh/id_rsa
    dest: /root/.ssh/id_rsa
    mode: 0600

- name: ensure github.com is a known host
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: checkout code
  git:
    repo: git@github.com:tsungchh/docker-nginx.git
    dest: /apps/nginx/
    key_file: /root/.ssh/id_rsa
    accept_hostkey: yes
    update: yes
    force: yes

- name: register tag var
  command: git log --pretty=format:'%h' -n 1
  args:
    chdir: /apps/nginx/
  register: tag

- debug: msg="docker image tag = {{ tag.stdout }}"

- name: Build, tag and push to docker hub
  docker_image:
    name: nginx
    path: /apps/nginx/
    tag: latest

- name     : fetch template from single remote host
  run_once : true
  fetch    :
    src             : /apps/nginx/configs/default.conf.j2
    dest            : ./roles/nginx/templates/nginx.conf.j2
    flat            : yes
    fail_on_missing : yes

- name: configure nginx sites
  template: src=nginx.conf.j2 dest=/apps/nginx/configs/default.conf mode=0644

- name:  Make sure a service is running
  systemd: 
    state: restarted 
    name: nginx
    enabled: yes